In [1]:
import torch

In [9]:
def get_parallel_db(db, remove_idx):
    return torch.cat((db[0:remove_idx], db[remove_idx + 1:]))


def get_parallel_dbs(db):
    pdbs = list()

    for i in range(len(db)):
        pdb = get_parallel_db(db, i)
        pdbs.append(pdb)

    return pdbs


def create_db_and_parallels(length):
    db = torch.rand(length) > 0.5
    pdb = get_parallel_dbs(db)
    return db, pdb


In [15]:
db, pdb = create_db_and_parallels(20)
pdb[0:4]

[tensor([1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1],
        dtype=torch.uint8),
 tensor([0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1],
        dtype=torch.uint8),
 tensor([0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1],
        dtype=torch.uint8),
 tensor([0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1],
        dtype=torch.uint8)]

In [16]:
def query(db):
    return db.sum()


In [17]:
query(db)

tensor(12)

tensor(12)