In [3]:
import torch

num_entries = 5000

db = torch.rand(num_entries) > 0.5
print(db)


tensor([0, 0, 0,  ..., 0, 1, 0], dtype=torch.uint8)

In [4]:
db.shape

torch.Size([5000])

In [7]:
db[0:9]


tensor([0, 0, 0, 0, 1, 1, 0, 0, 0], dtype=torch.uint8)

In [10]:
remove_entry = 4
db[0:4]
db[5:]

torch.cat((db[0:4], db[5:]))[0:9]

tensor([0, 0, 0, 0, 1, 0, 0, 0, 0], dtype=torch.uint8)

In [11]:
def get_parallel_db(db,remove_index):
    return torch.cat((db[0:remove_entry], db[remove_index+1:]))


In [13]:
get_parallel_db(db, 5).shape

torch.Size([4998])

In [14]:
def get_parallel_dbs(db):
    parallel_dbs = list()
    
    for i in range(len(db)):
        pdb = get_parallel_db(db,i)
        parallel_dbs.append(pdb)
        
    return parallel_dbs

In [16]:
pdbs = get_parallel_dbs(db)
(pdbs)[0:5]

[tensor([0, 0, 0,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([0, 0, 0,  ..., 0, 1, 0], dtype=torch.uint8)]

In [28]:
def create_db_and_parallels(num_entries):
    db = torch.rand(num_entries) > 0.5
    print(db[0:5])
    pdb = get_parallel_dbs(db)
    
    return db, pdb


In [29]:
db, pdb = create_db_and_parallels(5000)

tensor([1, 0, 1, 0, 1], dtype=torch.uint8)

In [30]:
db[0:5]
pdb[:6]

[tensor([1, 0, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 1, 0], dtype=torch.uint8),
 tensor([1, 0, 1,  ..., 0, 1, 0], dtype=torch.uint8)]