# Chapter 3

In [1]:
# copy previous funcation
import torch

def get_parallel_db(db, remove_idx):
    return torch.cat((db[0:remove_idx], db[remove_idx + 1:]))


def get_parallel_dbs(db):
    pdbs = list()

    for i in range(len(db)):
        pdb = get_parallel_db(db, i)
        pdbs.append(pdb)

    return pdbs


def create_db_and_parallels(length):
    db = torch.rand(length) > 0.5
    pdb = get_parallel_dbs(db)
    return db, pdb

In [24]:
db, pdbs = create_db_and_parallels(100)

In [25]:
true_results = torch.mean(db.float())
true_results

tensor(0.4200)

In [26]:
first_coin_flip = (torch.rand(len(db)) > 0.5).float()
second_coin_flip = (torch.rand(len(db)) > 0.5).float()

In [27]:
first_coin_flip

tensor([1., 1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1., 1.,
        0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 1.,
        1., 1., 0., 1., 1., 0., 1., 0., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 1.,
        1., 0., 1., 1., 0., 1., 0., 0., 1., 0.])

In [28]:
second_coin_flip

tensor([1., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0.,
        0., 1., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1.,
        0., 1., 1., 0., 0., 0., 0., 1., 1., 0., 1., 1., 1., 0., 0., 0., 0., 1.,
        0., 1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0.,
        1., 0., 1., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0.,
        1., 0., 0., 1., 0., 0., 0., 0., 0., 1.])

In [29]:
db.float() * first_coin_flip

tensor([1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
        1., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0.,
        0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
        0., 0., 1., 1., 0., 1., 0., 0., 0., 0.])

In [30]:
(1 - first_coin_flip)  * second_coin_flip

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
        0., 1., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
        0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.,
        0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 0., 1., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 1.])

In [31]:
arg_database = db.float() * first_coin_flip + (1 - first_coin_flip)  * second_coin_flip

In [32]:
arg_database

tensor([1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1.,
        0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0.,
        1., 0., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1.,
        0., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 1., 0.,
        0., 1., 1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 0., 1., 1., 0., 1., 1.,
        0., 0., 1., 1., 0., 1., 0., 0., 0., 1.])

In [34]:
torch.mean(arg_database.float()) * 2 - 0.5

tensor(0.4400)

In [45]:
def query(db):
    true_result = torch.mean(db.float())
    
    first_coin_flip = (torch.rand(len(db)) > 0.5).float()
    second_coin_flip = (torch.rand(len(db)) > 0.5).float()
    
    arg_db = (db.float() * first_coin_flip) + ((1-first_coin_flip) * second_coin_flip)
    
    result = torch.mean(arg_db.float()) * 2 - 0.5
    
    return result, true_result
    

In [49]:
db,_ = create_db_and_parallels(5000) 
query(db)

(tensor(0.5044), tensor(0.5030))

In [50]:
db,_ = create_db_and_parallels(10000) 
query(db)

(tensor(0.5144), tensor(0.5039))